title: Mindfulness Accepting Yourself and Everything Else
author: Ethan Hasman  
email: ethan@devocean.io
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  You’re welcome to join in contribute and share your Thoughts and insights about Mindfulness and the way it connects to your self experiance of the world and life.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ATHasman # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
